[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
set termguicolors     " enable true colors support
let ayucolor="dark"   " for dark version of theme
colorscheme ayu
'''

# https://wonwon-eater.com/neovim-susume-recommendation-plugin/#outline__4_9
[[plugins]]
repo='hoob3rt/lualine.nvim'
hook_add = '''
lua << LUA
require('lualine').setup {
  options = {
    icons_enabled = false,
    theme = 'auto',
    component_separators = {'', ''},
    section_separators = {'', ''},
    disabled_filetypes = {}
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch'},
    lualine_c = {
      {
        'filename',
        path = 1,
        'g:coc_status',
      }
    },
    lualine_x = {'encoding', 'fileformat', 'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {{'filename', path = 1}},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
LUA
'''

# https://wonwon-eater.com/neovim-susume-recommendation-plugin/#outline__4_21
[[plugins]]
repo = 'vim-test/vim-test'
depends = ['neoterm']
hook_add = '''
  nmap <silent> <leader>tn <cmd>update<cr><cmd>exec v:count.'Tclear'<cr><cmd>TestNearest<CR>
  nmap <silent> <leader>tf <cmd>update<cr><cmd>exec v:count.'Tclear'<cr><cmd>TestFile<CR>

  let g:neoterm_default_mod='vert botright'
  let g:neoterm_keep_term_open = 0
  let g:neoterm_autoscroll = 1
  let g:test#strategy = 'neoterm'
'''
[[plugins]]
repo = 'kassio/neoterm'

# https://wonwon-eater.com/neovim-susume-file-explorer/
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#default_hidden = 1
  nnoremap <leader>ef <cmd>Fern . -toggle -reveal=% -drawer<cr>
  nnoremap <leader>eo <cmd>Fern . -toggle -reveal=. -drawer<cr>
'''

# https://wonwon-eater.com/nvim-susume-fuzzy-finder/
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
  nnoremap <leader>p <cmd>Telescope find_files hidden=true theme=get_dropdown<cr>
  nnoremap <leader>gr <cmd>Telescope live_grep theme=get_dropdown<cr>
  nnoremap <leader>b <cmd>Telescope buffers theme=get_dropdown<cr>
  nnoremap <leader>h <cmd>Telescope oldfiles theme=get_dropdown<cr>
  nnoremap <leader>gb <cmd>Telescope git_branches theme=get_dropdown<cr>
'''
[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'
depends = ['telescope.nvim']
hook_post_source = '''
lua << LUA
require('telescope').setup{
  extensions = {
    fzf = {
      fuzzy = true,                    -- false will only do exact matching
      override_generic_sorter = false, -- override the generic sorter
      override_file_sorter = true,     -- override the file sorter
      case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
                                       -- the default case_mode is "smart_case"
    }
  }
}
require('telescope').load_extension('fzf')
LUA
'''

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'travisjeffery/vim-auto-mkdir'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'
hook_add = '''
lua << LUA
  vim.api.nvim_set_keymap('', '<leader>gh', "<Esc>:0GBrowse<CR>", { noremap = true })
LUA
'''

[[plugins]]
repo = 'github/copilot.vim'

##########
# LSP
##########
[[plugins]]
repo = 'neovim/nvim-lspconfig'
[[plugins]]
repo = 'mason-org/mason.nvim'
[[plugins]]
repo = 'mason-org/mason-lspconfig.nvim'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
