tap 'argon/mas'
tap 'caskroom/cask'
tap 'homebrew/brewdler'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'neovim/neovim'
brew 'pkg-config'
brew 'libyaml'
brew 'openssl'
brew 'ansible'
brew 'autoconf'
brew 'automake'
brew 'boost'
brew 'clipper'
brew 'cmake'
brew 'cocoapods'
brew 'colordiff'
brew 'libev'
brew 'libevent'
brew 'jansson'
brew 'libtool'
brew 'libxml2'
brew 'spdylay'
brew 'nghttp2'
brew 'curl', args: ['with-nghttp2']
brew 'gdbm'
brew 'gettext'
brew 'gibo'
brew 'mysql'
brew 'ocaml'
brew 'pcre'
brew 'readline'
brew 'rlwrap'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'zsh', args: ['without-etcdir']
brew 'argon/mas/mas'
cask 'adobe-reader'
cask 'android-studio'
cask 'anki'
cask 'atom'
cask 'chefdk'
cask 'coteditor'
cask 'cyberduck'
cask 'dash'
cask 'evernote'
cask 'filezilla'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'gyazo'
cask 'iterm2'
cask 'libreoffice'
cask 'mysqlworkbench'
cask 'pomodone'
cask 'sequel-pro'
cask 'shiftit'
cask 'skype'
cask 'slack'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'toggldesktop'
cask 'trello-x'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
mas 'GarageBand', id: 682658836
mas 'iMovie', id: 408981434
mas 'Pages', id: 409201541
mas 'WeChat', id: 836500024
mas 'LINE', id: 539883307
mas 'Keynote', id: 409183694
mas 'Xcode', id: 497799835
mas 'Numbers', id: 409203825
