tap 'caskroom/cask'
tap 'homebrew/bundle'
brew 'openssl'
brew 'libevent'
brew 'tmux'
brew 'vim'

cask 'atom'
cask 'filezilla'
cask 'sublime-text'
cask 'virtualbox'
cask 'vagrant'
cask 'vagrant-manager'
