[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'einars/js-beautify'

[[plugins]]
repo = 'evidens/vim-twig'

[[pulgins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'kylef/apiblueprint.vim'

[[plugins]]
repo = 'maksimr/vim-jsbeautify'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'soh335/vim-symfony'

[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'travisjeffery/vim-auto-mkdir'

[[plugins]]
repo = 'vim-scripts/autodate.vim'

[[plugins]]
repo = 'YankRing.vim'

[[plugins]]
repo = 'JSON.vim'
