[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete'
if   = '''has('lua')'''

[[plugins]]
repo = 'Shougo/neocomplcache'
if   = '''! has('lua')'''

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'travisjeffery/vim-auto-mkdir'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'vim-scripts/JSON.vim'

[[plugins]]
repo = 'millermedeiros/vim-esformatter'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = "pangloss/vim-javascript"

[[plugins]]
repo = "mxw/vim-jsx"

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'fatih/vim-go'
build = 'vim +GoInstallBinaries +q +q'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'joonty/vdebug'
